name: Run Selenium Test (C#)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # Specify .NET versions for testing
        dotnet-version: [6.0, 7.0]

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET SDK (version will be taken from the matrix)
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # Restore NuGet packages
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release

    # Run tests
    - name: Run Selenium tests
      run: |
        # Run your Selenium tests here
        dotnet test --configuration Release

    # Optionally, upload the test results as artifacts
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: TestResults/

    # Optionally, show the results from a previous step (e.g., using NUnit)
    - name: Show NUnit test results
      run: |
        mkdir TestResults
        echo "Test results will be available in TestResults/ folder"
