name: Run SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Use the version appropriate for your project

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Run SpecFlow tests
      run: dotnet test --filter FullyQualifiedName~YourSpecFlowTestNamespace

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/TestResults/*.xml'  # Adjust the path if needed to where your test results are generated.
